const COLOR_DATA = {
    blue:{
      "蔚蓝": {
        class: "black",
        title: "蔚蓝：类似晴朗天空的颜色的一种蓝色。",
        rgb: "rgb(112, 243, 255)",
        color16: "#70f3ff",
      },
      "蓝": {
        class: "black",
        title: "蓝：晴天空的颜色。",
        rgb: "rgb(68, 206, 246)",
        color16: "#44cef6",
      },
      "碧蓝": {
        class: "black",
        title: "碧蓝：青蓝色。",
        rgb: "rgb(62, 237, 231)",
        color16: "#3eede7",
      },
      "色青": {
        class: "white",
        title: "色青：依深浅分为－头青、二青、三青，用以画叶或山石。",
        rgb: "rgb(22, 133, 169)",
        color16: "#1685a9",
      },
      "靛青": {
        class: "white",
        title: "靛青：也叫“蓝靛”。用蓼蓝叶泡水调和与石灰沉淀所得的蓝色染料。呈深蓝绿色（注：有些地方将蓝墨水称为“靛水”或者“兰靛水”）。",
        rgb: "rgb(23, 124, 176)",
        color16: "#177cb0",
      },
      "靛蓝": {
        class: "white",
        title: "靛蓝：由植物(例如靛蓝或菘蓝属植物)得到的蓝色染料。",
        rgb: "rgb(6, 82, 121)",
        color16: "#065279",
      },
      "花青": {
        class: "white",
        title: "靛蓝：由植物(例如靛蓝或菘蓝属植物)得到的蓝色染料。",
        rgb: "rgb(0, 52, 114)",
        color16: "#003472",
      },
      "宝蓝": {
        class: "white",
        title: "宝蓝：鲜艳明亮的蓝色。",
        rgb: "rgb(75, 92, 196)",
        color16: "#4b5cc4",
      },
      "蓝灰色": {
        class: "black",
        title: "蓝灰色：一种近于灰略带蓝的深灰色。",
        rgb: "rgb(161, 175, 201)",
        color16: "#a1afc9",
      },
      "藏青": {
        class: "white",
        title: "藏青：蓝而近黑。",
        rgb: "rgb(46, 78, 126)",
        color16: "#2e4e7e",
      },
      "藏蓝": {
        class: "white",
        title: "藏蓝：蓝里略透红色。",
        rgb: "rgb(59, 46, 126)",
        color16: "#3b2e7e",
      },
      "黛": {
        class: "white",
        title: "黛：青黑色的颜料，古代女子用以画眉。",
        rgb: "rgb(74, 66, 102)",
        color16: "#4a4266",
      },
      "黛绿": {
        class: "white",
        title: "黛绿：墨绿。",
        rgb: "rgb(66, 102, 102)",
        color16: "#426666",
      },
      "黛蓝": {
        class: "white",
        title: "黛蓝：深蓝色。",
        rgb: "rgb(66, 80, 102)",
        color16: "#425066",
      },
      "黛紫": {
        class: "white",
        title: "黛紫：深紫色。",
        rgb: "rgb(87, 66, 102)",
        color16: "#574266",
      },
      "紫色": {
        class: "white",
        title: "紫色：蓝和红组成的颜色。古人以紫为祥瑞的颜色。代指与帝王、皇宫有关的事物。",
        rgb: "rgb(141, 75, 187)",
        color16: "#8d4bbb",
      },
      "紫酱": {
        class: "white",
        title: "紫酱：浑浊的紫色。",
        rgb: "rgb(129, 84, 99)",
        color16: "#815463",
      },
      "酱紫": {
        class: "white",
        title: "酱紫：紫中略带红的颜色。",
        rgb: "rgb(129, 84, 118)",
        color16: "#815476",
      },
      "紫檀": {
        class: "white",
        title: "紫檀：檀木的颜色，也称乌檀色乌木色。",
        rgb: "rgb(76, 34, 27)",
        color16: "#4c221b",
      },
      "绀青": {
        class: "white",
        title: "绀青：纯度较低的深紫色。",
        rgb: "rgb(0, 51, 113)",
        color16: "#003371",
      },
      "紫棠": {
        class: "white",
        title: "紫棠：黑红色。",
        rgb: "rgb(86, 0, 79)",
        color16: "#56004f",
      },
      "青莲": {
        class: "white",
        title: "青莲：偏蓝的紫色。",
        rgb: "rgb(128, 29, 174)",
        color16: "#801dae",
      },
      "群青": {
        class: "white",
        title: "群青：深蓝色。",
        rgb: "rgb(76, 141, 174)",
        color16: "#4c8dae",
      },
      "雪青": {
        class: "black",
        title: "雪青：浅蓝紫色。",
        rgb: "rgb(176, 164, 227)",
        color16: "#b0a4e3",
      },
      "丁香色": {
        class: "black",
        title: "丁香色：紫丁香的颜色，浅浅的紫色，很娇柔淡雅的色彩。",
        rgb: "rgb(204, 164, 227)",
        color16: "#cca4e3",
      },
      "藕色": {
        class: "black",
        title: "藕色：浅灰而略带红的颜色。",
        rgb: "rgb(204, 164, 227)",
        color16: "#edd1d8",
      },
      "藕荷色": {
        class: "black",
        title: "藕荷色：浅紫而略带红的颜色。",
        rgb: "rgb(228, 198, 208)",
        color16: "#e4c6d0",
      },
    },
    red: {
      "朱砂": {
        class: "white",
        title: "朱砂：色朱红。用以画花卉、禽鸟羽毛。",
        rgb: "rgb(255, 70, 31)",
        color16: "#ff461f",
      },
      "火红": {
        class: "white",
        title: "火红：火焰的红色，赤色。",
        rgb: "rgb(255, 45, 81)",
        color16: "#ff2d51",
      },
      "朱膘": {
        class: "white",
        title: "朱膘：色橘红。明度比朱砂高，彩度比朱砂低。用以画花卉。",
        rgb: "rgb(243, 104, 56)",
        color16: "#f36838",
      },
      "妃色": {
        class: "white",
        title: "妃色：妃红色，古同“绯”，粉红色。杨妃色、湘妃色、粉红皆同义。",
        rgb: "rgb(237, 87, 54)",
        color16: "#ed5736",
      },
      "品红": {
        class: "white",
        title: "品红：比大红浅的红色。",
        rgb: "rgb(240, 0, 86)",
        color16: "#f00056",
      },
      "粉红": {
        class: "black",
        title: "粉红：即浅红色。别称：妃色、杨妃色、湘妃色、妃红色。",
        rgb: "rgb(255, 179, 167)",
        color16: "#ffb3a7",
      },
      "桃红": {
        class: "black",
        title: "桃红：桃花的颜色，比粉红略鲜润的颜色。",
        rgb: "rgb(244, 121, 131)",
        color16: "#f47983",
      },
      "海棠红": {
        class: "black",
        title: "海棠红：淡紫红色、较桃红色深一些，是非常妩媚娇艳的颜色。",
        rgb: "rgb(219, 90, 107)",
        color16: "#db5a6b",
      },
      "樱桃色": {
        class: "black",
        title: "樱桃色：鲜红色。",
        rgb: "rgb(201, 55, 86)",
        color16: "#c93756",
      },
      "酡颜": {
        class: "black",
        title: "酡颜：饮酒脸红的样子。亦泛指脸红色。",
        rgb: "rgb(249, 144, 111)",
        color16: "#f9906f",
      },
      "银红": {
        class: "black",
        title: "银红：银朱和粉红色颜料配成的颜色。多用来形容有光泽的各种红色，尤指有光泽浅红。",
        rgb: "rgb(240, 86, 84)",
        color16: "#f05654",
      },
      "大红": {
        class: "white",
        title: "大红：正红色，三原色中的红，传统的中国红，又称绛色。",
        rgb: "rgb(255, 33, 33)",
        color16: "#ff2121",
      },
      "石榴红": {
        class: "white",
        title: "石榴红：石榴花的颜色，高色度和纯度的红色。",
        rgb: "rgb(242, 12, 0)",
        color16: "#f20c00",
      },
      "绛紫": {
        class: "white",
        title: "绛紫：紫中略带红的颜色。",
        rgb: "rgb(140, 67, 86)",
        color16: "#8c4356",
      },
      "绯红": {
        class: "white",
        title: "绯红：艳丽的深红。",
        rgb: "rgb(200, 60, 35)",
        color16: "#c83c23",
      },
      "胭脂": {
        class: "white",
        title: "胭脂：1、女子装扮时用的胭脂的颜色。2、国画暗红色颜料。",
        rgb: "rgb(157, 41, 51)",
        color16: "#9d2933",
      },
      "朱红": {
        class: "white",
        title: "朱红：朱砂的颜色，比大红活泼，也称铅朱、朱色、丹色。",
        rgb: "rgb(255, 76, 0)",
        color16: "#ff4c00",
      },
      "丹": {
        class: "white",
        title: "丹：丹砂的鲜艳红色。",
        rgb: "rgb(255, 78, 32)",
        color16: "#ff4e20",
      },
      "酡红": {
        class: "white",
        title: "酡红：像饮酒后脸上泛现的红色，泛指脸红。",
        rgb: "rgb(220, 48, 35)",
        color16: "#dc3023",
      },    
      "炎": {
        class: "white",
        title: "炎：引申为红色。",
        rgb: "rgb(255, 51, 0)",
        color16: "#ff3300",
      },    
      "茜色": {
        class: "white",
        title: "茜色：茜草染的色彩，呈深红色。",
        rgb: "rgb(203, 58, 86)",
        color16: "#cb3a56",
      },    
      "绾": {
        class: "black",
        title: "绾：绛色，浅绛色。",
        rgb: "rgb(169, 129, 117)",
        color16: "#a98175",
      },        
      "檀": {
        class: "black",
        title: "檀：浅红色，浅绛色。",
        rgb: "rgb(179, 109, 97)",
        color16: "#b36d61",
      },        
      "嫣红": {
        class: "black",
        title: "嫣红：鲜艳的红色。",
        rgb: "rgb(239, 122, 130)",
        color16: "#ef7a82",
      },        
      "洋红": {
        class: "black",
        title: "洋红：色橘红，用以画花卉。",
        rgb: "rgb(255, 71, 119)",
        color16: "#ff4777",
      },        
      "枣红": {
        class: "white",
        title: "枣红：即深红。",
        rgb: "rgb(195, 33, 54)",
        color16: "#c32136",
      },          
      "殷红": {
        class: "white",
        title: "殷红：发黑的红色。",
        rgb: "rgb(190, 0, 47)",
        color16: "#be002f",
      },          
      "赫赤": {
        class: "white",
        title: "赫赤：深红，火红。泛指赤色、火红色。",
        rgb: "rgb(201, 31, 55)",
        color16: "#c91f37",
      },          
      "银朱": {
        class: "white",
        title: "银朱：呈暗粉色。",
        rgb: "rgb(191, 36, 42)",
        color16: "#bf242a",
      },          
      "赤": {
        class: "white",
        title: "赤：本义火的颜色，即红色。",
        rgb: "rgb(195, 39, 43)",
        color16: "#c3272b",
      },
      "栗色": {
        class: "white",
        title: "栗色：栗壳的颜色，即紫黑色。",
        rgb: "rgb(96, 40, 30)",
        color16: "#60281e",
      },
      "玄色": {
        class: "white",
        title: "玄色：赤黑色，黑中带红的颜色，又泛指黑色。",
        rgb: "rgb(98, 42, 29)",
        color16: "#622a1d",
      },
    },
    green: {
      "松花色": {
        class: "black",
        title: "松花色：浅黄绿色，松树花粉的颜色，《红楼梦》中提及松花配桃红为娇艳。",
        rgb: "rgb(188, 230, 114)",
        color16: "#bce672",
      },
      "柳黄": {
        class: "black",
        title: "柳黄：像柳树芽那样的浅黄色。",
        rgb: "rgb(201, 221, 34)",
        color16: "#c9dd22",
      },
      "嫩绿": {
        class: "black",
        title: "嫩绿：像刚长出的嫩叶的浅绿色。",
        rgb: "rgb(189, 221, 34)",
        color16: "#bddd22",
      },
      "柳绿": {
        class: "black",
        title: "柳绿：柳叶的青绿色。",
        rgb: "rgb(175, 221, 34)",
        color16: "#afdd22",
      },
      "葱黄": {
        class: "black",
        title: "葱黄：黄绿色，嫩黄色。",
        rgb: "rgb(163, 217, 0)",
        color16: "#a3d900",
      },
      "葱绿": {
        class: "black",
        title: "葱绿：1、浅绿又略显微黄的颜色，2、草木青翠的样子。",
        rgb: "rgb(158, 217, 0)",
        color16: "#9ed900",
      },
      "豆绿": {
        class: "black",
        title: "豆绿：浅黄绿色。",
        rgb: "rgb(158, 217, 0)",
        color16: "#9ed900",
      },
      "豆青": {
        class: "black",
        title: "豆青：浅青绿色。",
        rgb: "rgb(150, 206, 84)",
        color16: "#96ce54",
      },
      "油绿": {
        class: "black",
        title: "油绿：光润而浓绿的颜色。",
        rgb: "rgb(0, 188, 18)",
        color16: "#00bc12",
      },
      "葱倩": {
        class: "black",
        title: "葱倩：青绿色。",
        rgb: "rgb(14, 184, 58)",
        color16: "#0eb83a",
      },
      "葱青": {
        class: "black",
        title: "葱倩：淡淡的青绿色。",
        rgb: "rgb(14, 184, 58)",
        color16: "#0eb83a",
      },
      "青葱": {
        class: "black",
        title: "青葱：翠绿色,形容植物浓绿。",
        rgb: "rgb(10, 163, 68)",
        color16: "#0aa344",
      },
      "石绿": {
        class: "black",
        title: "石绿：依深浅分为－头绿、二绿、三绿。用以画山石、树干、叶、点苔等。",
        rgb: "rgb(22, 169, 81)",
        color16: "#16a951",
      },
      "松柏绿": {
        class: "black",
        title: "松柏绿：经冬松柏叶的深绿。",
        rgb: "rgb(33, 166, 117)",
        color16: "#21a675",
      },
      "松花绿": {
        class: "black",
        title: "松花绿：亦作“松花”、“松绿”。偏黑的深绿色,墨绿。",
        rgb: "rgb(5, 119, 72)",
        color16: "#057748",
      },
      "绿沈": {
        class: "black",
        title: "绿沈（沉）：深绿。",
        rgb: "rgb(12, 137, 24)",
        color16: "#0c8918",
      },
      "绿色": {
        class: "black",
        title: "绿色：、1本义：青中带黄的颜色。2、引申为黑色，如绿鬓：乌黑而光亮的鬓发。代指为青春年少的容颜。",
        rgb: "rgb(0, 229, 0)",
        color16: "#00e500",
      },
      "草绿": {
        class: "black",
        title: "草绿：绿而略黄的颜色。",
        rgb: "rgb(64, 222, 90)",
        color16: "#40de5a",
      },
      "青翠": {
        class: "black",
        title: "青翠：鲜绿。",
        rgb: "rgb(0, 224, 121)",
        color16: "#00e079",
      },
      "青色": {
        class: "black",
        title: "青色：1、一类带绿的蓝色,中等深浅,高度饱和。3、本义是蓝色。4、一般指深绿色。5、也指黑色。6、四色印刷中的一色。7、特指三补色中的一色。",
        rgb: "rgb(0, 224, 158)",
        color16: "#00e09e",
      },
      "翡翠色": {
        class: "black",
        title: "翡翠色：1、翡翠鸟羽毛的青绿色。2、翡翠宝石的颜色。",
        rgb: "rgb(61, 225, 173)",
        color16: "#3de1ad",
      },
      "碧绿": {
        class: "black",
        title: "碧绿：鲜艳的青绿色。",
        rgb: "rgb(42, 221, 156)",
        color16: "#2add9c",
      },
      "玉色": {
        class: "black",
        title: "玉色：玉的颜色，高雅的淡绿、淡青色。",
        rgb: "rgb(46, 223, 163)",
        color16: "#2edfa3",
      },
      "缥": {
        class: "black",
        title: "缥：绿色而微白。",
        rgb: "rgb(127, 236, 173)",
        color16: "#7fecad",
      },
      "艾绿": {
        class: "black",
        title: "艾绿：艾草的颜色。偏苍白的绿色。",
        rgb: "rgb(164, 226, 198)",
        color16: "#a4e2c6",
      },
      "石青": {
        class: "black",
        title: "石青：色青，依深浅分为－头青、二青、三青。用以画叶或山石。",
        rgb: "rgb(123, 207, 166)",
        color16: "#7bcfa6",
      },
      "碧色": {
        class: "black",
        title: "碧色：1、青绿色。2、青白色,浅蓝色。",
        rgb: "rgb(27, 209, 165)",
        color16: "#1bd1a5",
      },
      "青碧": {
        class: "black",
        title: "青碧：鲜艳的青蓝色。",
        rgb: "rgb(72, 192, 163)",
        color16: "#48c0a3",
      },
      "铜绿": {
        class: "black",
        title: "铜绿：铜氧化后的色彩。",
        rgb: "rgb(84, 150, 136)",
        color16: "#549688",
      },
      "竹青": {
        class: "black",
        title: "竹青：竹子的绿色。",
        rgb: "rgb(120, 146, 98)",
        color16: "#789262",
      },
      "墨灰": {
        class: "white",
        title: "墨灰：即黑灰。",
        rgb: "rgb(117, 138, 153)",
        color16: "#758a99",
      },
      "墨色": {
        class: "white",
        title: "墨色：即墨黑色。",
        rgb: "rgb(80, 97, 109)",
        color16: "#50616d",
      },
      "鸦青": {
        class: "white",
        title: "鸦青：鸦羽的颜色，即黑而带有紫绿光的颜色。",
        rgb: "rgb(66, 76, 80)",
        color16: "#424c50",
      },
      "黯": {
        class: "white",
        title: "黯：深黑色，泛指黑色。",
        rgb: "rgb(65, 85, 93)",
        color16: "#41555d",
      },
    },
    yellow: {
      "樱草色": {
        class: "black",
        title: "樱草色：淡黄色。",
        rgb: "rgb(234, 255, 86)",
        color16: "#eaff56",
      },
      "鹅黄": {
        class: "black",
        title: "鹅黄：淡黄色。",
        rgb: "rgb(255, 241, 67)",
        color16: "#fff143",
      },
      "鸭黄": {
        class: "black",
        title: "鸭黄：小鸭毛的黄色。",
        rgb: "rgb(250, 255, 114)",
        color16: "#faff72",
      },
      "杏黄": {
        class: "black",
        title: "杏黄：成熟杏子的黄色。",
        rgb: "rgb(255, 166, 49)",
        color16: "#ffa631",
      },
      "橙黄": {
        class: "black",
        title: "橙黄：橙子的黄色。",
        rgb: "rgb(255, 164, 0)",
        color16: "#ffa400",
      },
      "橙色": {
        class: "black",
        title: "橙色：界于红色和黄色之间的混合色。",
        rgb: "rgb(250, 140, 53)",
        color16: "#fa8c35",
      },
      "杏红": {
        class: "black",
        title: "杏红：成熟杏子偏红色的一种颜色。",
        rgb: "rgb(255, 140, 49)",
        color16: "#ff8c31",
      },
      "橘黄": {
        class: "black",
        title: "橘黄：柑橘的黄色。",
        rgb: "rgb(255, 137, 54)",
        color16: "#ff8936",
      },
      "橘红": {
        class: "black",
        title: "橘红：柑橘皮所呈现的红色。",
        rgb: "rgb(255, 117, 0)",
        color16: "#ff7500",
      },
      "藤黄": {
        class: "black",
        title: "藤黄：明黄色。南方热带林中的海藤树，常绿乔木，茎高达二十米，从其树皮凿孔，流出黄色树脂，以竹筒承接，干透可作国画颜料。",
        rgb: "rgb(255, 182, 30)",
        color16: "#ffb61e",
      },
      "姜黄": {
        class: "black",
        title: "姜黄：中药名，别名黄姜。为姜科植物姜黄的根茎。又指人脸色不正,呈黄白色。",
        rgb: "rgb(255, 199, 115)",
        color16: "#ffc773",
      },
      "雌黄": {
        class: "black",
        title: "雌黄：矿物名。成分是三硫化二砷（As2S3）橙黄色,半透明,可用来制颜料。古人用雌黄来涂改文字，因此称乱改文字、乱发议论为妄下雌黄，称不顾事实、随口乱说为信口雌黄。",
        rgb: "rgb(255, 198, 75)",
        color16: "#ffc64b",
      },
      "赤金": {
        class: "black",
        title: "赤金：足金的颜色。",
        rgb: "rgb(242, 190, 69)",
        color16: "#f2be45",
      },
      "缃色": {
        class: "black",
        title: "缃色：浅黄色。",
        rgb: "rgb(240, 194, 57)",
        color16: "#f0c239",
      },
      "雄黄": {
        class: "black",
        title: "雄黄：中药名。为含硫化砷的矿石。别名石黄、黄石。",
        rgb: "rgb(233, 187, 29)",
        color16: "#e9bb1d",
      },
      "秋香色": {
        class: "black",
        title: "秋香色：浅橄榄色 浅黄绿色。",
        rgb: "rgb(217, 182, 17)",
        color16: "#d9b611",
      },
      "金色": {
        class: "black",
        title: "金色：平均为深黄色带光泽的颜色。",
        rgb: "rgb(234, 205, 118)",
        color16: "#eacd76",
      },
      "牙色": {
        class: "black",
        title: "牙色：与象牙相似的淡黄色。",
        rgb: "rgb(238, 222, 176)",
        color16: "#eedeb0",
      },
      "枯黄": {
        class: "black",
        title: "枯黄：干枯焦黄。",
        rgb: "rgb(211, 177, 125)",
        color16: "#d3b17d",
      },
      "黄栌": {
        class: "black",
        title: "黄栌：一种落叶灌木，花黄绿色,叶子秋天变成红色。木材黄色可做染料。",
        rgb: "rgb(226, 156, 69)",
        color16: "#e29c45",
      },
      "乌金": {
        class: "black",
        title: "乌金：1、暗金色，金子氧化后的颜色。2、中药上指墨。",
        rgb: "rgb(226, 156, 69)",
        color16: "#e29c45",
      },
      "昏黄": {
        class: "black",
        title: "昏黄：形容天色、灯光等呈幽暗的黄色。",
        rgb: "rgb(200, 155, 64)",
        color16: "#c89b40",
      },
      "棕黄": {
        class: "black",
        title: "棕黄：浅褐色。",
        rgb: "rgb(174, 112, 0)",
        color16: "#ae7000",
      },
      "琥珀": {
        class: "black",
        title: "琥珀：琥珀的颜色。",
        rgb: "rgb(202, 105, 36)",
        color16: "#ca6924",
      },
      "棕色": {
        class: "white",
        title: "棕色：棕毛的颜色，即褐色。",
        rgb: "rgb(178, 93, 37)",
        color16: "#b25d25",
      },
      "茶色": {
        class: "white",
        title: "茶色：茶的颜色，比栗色稍红的棕橙色至浅棕色。",
        rgb: "rgb(179, 92, 68)",
        color16: "#b35c44",
      },
      "棕红": {
        class: "white",
        title: "棕红：红褐色。",
        rgb: "rgb(155, 68, 0)",
        color16: "#9b4400",
      },
      "赭": {
        class: "white",
        title: "赭：赤红如赭土的颜料，古人用以饰面。",
        rgb: "rgb(156, 83, 51)",
        color16: "#9c5333",
      },
      "赭色": {
        class: "black",
        title: "赭色：红色、赤红色。",
        rgb: "rgb(149, 85, 57)",
        color16: "#955539",
      },
      "赭石": {
        class: "black",
        title: "赭石：暗棕色矿物，用做颜料。",
        rgb: "rgb(132, 90, 51)",
        color16: "#845a33",
      },
      "驼色": {
        class: "black",
        title: "驼色：一种比咔叽色稍红而微淡、比肉桂色黄而稍淡和比核桃棕色黄而暗的浅黄棕色。",
        rgb: "rgb(168, 132, 98)",
        color16: "#a88462",
      },
      "秋色": {
        class: "black",
        title: "秋色：1、中常橄榄棕色,它比一般橄榄棕色稍暗,且稍稍绿些。2、古以秋为金,其色白,故代指白色。",
        rgb: "rgb(137, 108, 57)",
        color16: "#896c39",
      },
      "棕绿": {
        class: "black",
        title: "棕绿：绿中泛棕色的一种颜色。",
        rgb: "rgb(130, 113, 0)",
        color16: "#827100",
      },
      "褐色": {
        class: "black",
        title: "褐色：黄黑色。",
        rgb: "rgb(110, 81, 30)",
        color16: "#6e511e",
      },
      "棕黑": {
        class: "black",
        title: "棕黑：深棕色。",
        rgb: "rgb(124, 75, 0)",
        color16: "#7c4b00",
      }
    },
    white: {
      "银白": {
        class: "black",
        title: "银白：带银光的白色。",
        rgb: "rgb(233, 231, 239)",
        color16: "#e9e7ef",
      },
      "铅白": {
        class: "black",
        title: "铅白：铅粉的白色。铅粉，国画颜料，日久易氧化“返铅”变黑。铅粉在古时用以搽脸的化妆品。",
        rgb: "rgb(240, 240, 244)",
        color16: "#f0f0f4",
      },
      "霜色": {
        class: "black",
        title: "霜色：白霜的颜色。",
        rgb: "rgb(233, 241, 246)",
        color16: "#e9f1f6",
      },
      "雪白": {
        class: "black",
        title: "雪白：如雪般洁白。",
        rgb: "rgb(240, 252, 255)",
        color16: "#f0fcff",
      },
      "莹白": {
        class: "black",
        title: "莹白：晶莹洁白。",
        rgb: "rgb(227, 249, 253)",
        color16: "#e3f9fd",
      },
      "月白": {
        class: "black",
        title: "月白：淡蓝色，月光的颜色。",
        rgb: "rgb(214, 236, 240)",
        color16: "#d6ecf0",
      },
      "象牙白": {
        class: "black",
        title: "象牙白：乳白色，象牙的颜色。",
        rgb: "rgb(255, 251, 240)",
        color16: "#fffbf0",
      },
      "缟": {
        class: "black",
        title: "缟：白色。",
        rgb: "rgb(242, 236, 222)",
        color16: "#f2ecde",
      },
      "鱼肚白": {
        class: "black",
        title: "鱼肚白：似鱼腹部的颜色，多指黎明时东方的天色颜色。",
        rgb: "rgb(252, 239, 232)",
        color16: "#fcefe8",
      },
      "白粉": {
        class: "black",
        title: "白粉：亦称胡粉，色白，有蛤粉和铅粉两种。用以画白花、鸟，或调配其他颜料使用。",
        rgb: "rgb(255, 242, 223)",
        color16: "#fff2df",
      },
      "荼白": {
        class: "black",
        title: "荼白：如荼之白色。",
        rgb: "rgb(243, 249, 241)",
        color16: "#f3f9f1",
      },
      "鸭卵青": {
        class: "black",
        title: "鸭卵青：淡青灰色，极淡的青绿色，似鸭蛋壳的颜色。",
        rgb: "rgb(243, 249, 241)",
        color16: "#f3f9f1",
      },
      "素": {
        class: "black",
        title: "素：白色，无色。",
        rgb: "rgb(224, 240, 233)",
        color16: "#e0f0e9",
      },
      "青白": {
        class: "black",
        title: "青白：白而发青,尤指脸没有血色。",
        rgb: "rgb(192, 235, 215)",
        color16: "#c0ebd7",
      },
      "蟹壳青": {
        class: "black",
        title: "蟹壳青：深灰绿色。",
        rgb: "rgb(187, 205, 197)",
        color16: "#bbcdc5",
      },
      "花白": {
        class: "black",
        title: "花白：白色和黑色混杂的、斑白的、夹杂有灰色的白。",
        rgb: "rgb(187, 205, 197)",
        color16: "#bbcdc5",
      },
      "老银": {
        class: "black",
        title: "老银：银氧化后的颜色。",
        rgb: "rgb(186, 202, 198)",
        color16: "#bacac6",
      },
      "灰色": {
        class: "black",
        title: "灰色：黑色和白色混和成的一种颜色。",
        rgb: "rgb(128, 128, 128)",
        color16: "#808080",
      },
      "苍色": {
        class: "black",
        title: "苍色：本义草色，古义是青黑色，今义是灰白色。",
        rgb: "rgb(117, 135, 138)",
        color16: "#75878a",
      },
      "水色": {
        class: "black",
        title: "水色：水面呈现的色泽，也指淡青色，接近白色。",
        rgb: "rgb(136, 173, 166)",
        color16: "#88ada6",
      },
      "黝": {
        class: "white",
        title: "黝：本义为淡黑色或微青黑色。",
        rgb: "rgb(107, 104, 130)",
        color16: "#6b6882",
      },
      "乌色": {
        class: "white",
        title: "乌色：暗而呈黑的颜色。",
        rgb: "rgb(114, 94, 130)",
        color16: "#725e82",
      },
      "玄青": {
        class: "white",
        title: "玄青：深黑色。",
        rgb: "rgb(61, 59, 79)",
        color16: "#3d3b4f",
      },
      "乌黑": {
        class: "white",
        title: "乌黑：深黑，漆黑。",
        rgb: "rgb(57, 47, 65)",
        color16: "#392f41",
      },
      "黎": {
        class: "white",
        title: "黎：黑中带黄似黎草色。",
        rgb: "rgb(117, 102, 77)",
        color16: "#75664d",
      },
      "黧": {
        class: "white",
        title: "黧：黑中带黄的颜色。",
        rgb: "rgb(93, 81, 60)",
        color16: "#5d513c",
      },
      "黝黑": {
        class: "white",
        title: "黝黑：青黑色。",
        rgb: "rgb(102, 87, 87)",
        color16: "#665757",
      },
      "缁色": {
        class: "white",
        title: "缁色：帛黑色。",
        rgb: "rgb(73, 49, 49)",
        color16: "#493131",
      },
      "煤黑": {
        class: "white",
        title: "煤黑：煤的颜色。",
        rgb: "rgb(49, 37, 32)",
        color16: "#312520",
      },
      "漆黑": {
        class: "white",
        title: "漆黑：非常黑。",
        rgb: "rgb(22, 24, 35)",
        color16: "#161823",
      },
    }
  };

  const rootDom = document.getElementById('test');

  for(let index in COLOR_DATA) {
    const colorClassDom = strToDom("<ul id = '"+index+"'>");
    rootDom.appendChild(colorClassDom);
    const listColor = document.getElementById(index);
    for(let color in COLOR_DATA[index]) {
      const domText = '<li title="' + COLOR_DATA[index][color].title + '" class="' + COLOR_DATA[index][color].class + '" style="background: ' + COLOR_DATA[index][color].rgb + '"><a>' + color + '<span  data-clipboard-text="' + COLOR_DATA[index][color].color16+'">' + COLOR_DATA[index][color].color16 + '</span></a></li>';
      const colorDom = strToDom(domText);
        listColor.appendChild(colorDom);
    }
  }

  function strToDom(str) {
  　　 const objE = document.createElement('div');
  　　 objE.innerHTML = str;
  　　 return objE.childNodes[0];
  };